In [1]:
import numpy as np

Nama : Audita Bella Intan Puspita

### Nomer 1

In [16]:
mulai = int(input("Masukkan nilai mulai: "))
selesai = int(input("Masukkan nilai selesai: "))

#1dimensi

array = np.arange(mulai, selesai+1)
print("Array hasil:")
print(array)

# 2 dimensi

array_2d = array.reshape(3,9)
print("Array versi 2D: ")
print(array_2d)

# 3 dimensi
array_3d = array.reshape(3, 3, 3)
print("Array versi 3D: ")
print(array_3d)



Array hasil:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28]


ValueError: cannot reshape array of size 28 into shape (3,9)

### Nomer 2

In [15]:
n = int(input("Masukkan Banyak data: "))
angka_mulai = int(input("Masukkan angka mulai: "))
angka_berakhir = int(input("Masukkan angka berakhir: "))

random_array = np.random.randint(angka_mulai, angka_berakhir + 1, n)
print("Array 1 dimensi:")
print(random_array)

dua_dimensi = random_array.reshape(4, 4)
print("Dua Dimensi:")
print(dua_dimensi)

matrix_flipped = dua_dimensi[:, ::-1]
print("Tukar posisi:")
print(matrix_flipped)

Array 1 dimensi:
[22 10 49 46 17 19 12 11 27  8  4 45 48  6 23 26]
Dua Dimensi:
[[22 10 49 46]
 [17 19 12 11]
 [27  8  4 45]
 [48  6 23 26]]
Tukar posisi:
[[46 49 10 22]
 [11 12 19 17]
 [45  4  8 27]
 [26 23  6 48]]


### Nomer 3

In [11]:
array = np.full((10,10), 4)
array[1:-1, 1:-1] = 0

print(array)

[[4 4 4 4 4 4 4 4 4 4]
 [4 0 0 0 0 0 0 0 0 4]
 [4 0 0 0 0 0 0 0 0 4]
 [4 0 0 0 0 0 0 0 0 4]
 [4 0 0 0 0 0 0 0 0 4]
 [4 0 0 0 0 0 0 0 0 4]
 [4 0 0 0 0 0 0 0 0 4]
 [4 0 0 0 0 0 0 0 0 4]
 [4 0 0 0 0 0 0 0 0 4]
 [4 4 4 4 4 4 4 4 4 4]]
