In [1]:
import numpy as np
a = np.array ([1,2,3])

### Array

In [2]:
a

array([1, 2, 3])

In [3]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [5]:
np.empty(6)

array([1., 1., 1., 1., 1., 1.])

In [6]:
print (np.arange(4))
print(np.arange(0,10,2))

[0 1 2 3]
[0 2 4 6 8]


### Add, Remove, and Sort

In [10]:
arr = np.array([1,2,3,4,5,6,7,8])
np.append(arr, [1,2])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [11]:
np.delete(arr,1)

array([1, 3, 4, 5, 6, 7, 8])

In [12]:
arr = np.array([2,1,5,3,7,4,6,8])

In [13]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

### Shape and Size

In [15]:
array_example = np.array([
    [[0,1,2,3],
     [4,5,6,7]],

    [[0,1,2,3],
     [4,5,6,7]],

    [[0,1,2,3],
     [4,5,6,7]]])

print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [16]:
array_example.ndim

3

In [17]:
array_example.size

24

In [18]:
array_example.shape

(3, 2, 4)

In [19]:
arr_one = np.array([[1,2,3,4,5]])

In [20]:
arr_one.ndim

2

In [21]:
arr_one.size

5

In [22]:
arr_one.shape

(1, 5)

### Reshape

In [23]:
a = np.arange(6)
print (a)

[0 1 2 3 4 5]


In [24]:
b = a.reshape(3,2)
print (b)

[[0 1]
 [2 3]
 [4 5]]


In [25]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

### Convert 1D to 2D

In [26]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [27]:
a2 = a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [28]:
row_vector = a[np.newaxis, :]
print(row_vector.shape)
print(row_vector)

(1, 6)
[[1 2 3 4 5 6]]


In [29]:
col_vector = a[:, np.newaxis]
print(col_vector.shape)
print(col_vector)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [30]:
a = np.array ([1,2,3,4,5,6])
a.shape

(6,)

In [32]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [33]:
c = np.expand_dims(a, axis = 0)
c.shape

(1, 6)

### Indexing and Slicing

In [34]:
data = np.array([1,2,3])

print(data)
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

[1 2 3]
1
2
[1 2]
[2 3]
[2 3]


In [35]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [36]:
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]


In [38]:
five_up = (a >= 5)

print(a[five_up])
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]
[ 5  6  7  8  9 10 11 12]


In [39]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [41]:
c = a[(a>2) & (a<11)]
print(c)

[ 3  4  5  6  7  8  9 10]


### Creating Array from Existing Data

In [42]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

In [43]:
arr1 = arr[3:8]

In [44]:
arr1 = arr[3:8]
arr1

array([4, 5, 6, 7, 8])

In [48]:

a_1 = np.array([[1,1],
                [2,2]])

In [49]:

a_2 = np.array([[3,3],
                [4,4]])

In [50]:
np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [51]:
np.hstack((a_1,a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [55]:
arrsplit = np.array([[1,2,3,4,5,6,7,8,9,10,11,12],
[13,14,15,16,17,18,19,20,21,22,23,24]])

print(arrsplit)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [56]:
np.hsplit(arrsplit,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [57]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [58]:
b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [59]:
c = a.copy()
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### Basic array Operations

In [61]:
a  = np.array([1,2,3,4])
a.sum()

10

In [62]:
b = np.array([[1,1],[2,2]])
b

array([[1, 1],
       [2, 2]])

In [63]:
b.sum(axis=0)

array([3, 3])

In [64]:
b.sum(axis=1)

array([2, 4])

In [65]:
data = np.array([1,2])
data

array([1, 2])

In [66]:
ones = np.ones(2)
ones

array([1., 1.])

In [67]:
data + ones

array([2., 3.])

In [68]:
data * data

array([1, 4])

In [69]:
data / data

array([1., 1.])

### Broadcasting

In [70]:
data * 2

array([2, 4])

### More Array Operations

In [71]:
A = np.array ([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
               [0.54627315, 0.05093587, 0.40067661, 0.55645993],
               [0.12697628, 0.82485143, 0.26590556, 0.56917101]])
print(A)

[[0.45053314 0.17296777 0.34376245 0.5510652 ]
 [0.54627315 0.05093587 0.40067661 0.55645993]
 [0.12697628 0.82485143 0.26590556 0.56917101]]


In [73]:
A.sum()

4.8595784

In [74]:
A.min()

0.05093587

In [75]:
A.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [76]:
A.max()

0.82485143

In [77]:
A.max(axis=1)

array([0.5510652 , 0.55645993, 0.82485143])

In [78]:
A.std()

0.21392120766089617

### Creating Matrices

In [80]:
np.ones((3,2))
np.zeros((3,2))
np.random.random((3,2))

print(np.ones((3,2)))
print(np.zeros((3,2)))
print(np.random.random((3,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.77525289 0.60556767]
 [0.31185531 0.70673345]
 [0.29666939 0.85227879]]


In [81]:
data = np.array([[1,2], [3,4]])
print(data)

[[1 2]
 [3 4]]


In [82]:
ones = np.ones([2,2])
print (ones)

[[1. 1.]
 [1. 1.]]


In [83]:
print(data + ones)

[[2. 3.]
 [4. 5.]]


In [84]:
ones_row = np.ones([1,2])
print(ones_row)

[[1. 1.]]


In [85]:
print(data + ones_row)

[[2. 3.]
 [4. 5.]]


In [87]:
a_1 = np.array([[1,2,3],[4,5,6]])
print(a_1)
print(a_1.shape)

a_2 = np.array([[7,8],[9,10], [11,12]])
print(a_2)
print(a_2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[ 7  8]
 [ 9 10]
 [11 12]]
(3, 2)


In [88]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

### Matrix Indexing

In [89]:
data = np.array([[1,2],[3,4],[5,6]])

print(data)
print(data[0])
print(data[1])
print(data[2])
print(data[0,1])
print(data[1:3])
print(data[0:2,1])



[[1 2]
 [3 4]
 [5 6]]
[1 2]
[3 4]
[5 6]
2
[[3 4]
 [5 6]]
[2 4]


### Matrix Aggregation

In [90]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [91]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [92]:
print(data.max(axis=0))
print(data.max(axis=1))

[5 6]
[2 4 6]


In [93]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [94]:
print(data.T)

[[1 3 5]
 [2 4 6]]


In [95]:
data_col = np.array([[1,2,3,4,5,6]]).T
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [96]:
data_col.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [97]:
data_col.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [98]:
arr = np.arange(6).reshape((2,3))
print(arr)

[[0 1 2]
 [3 4 5]]


In [99]:
ndarr = np.array([[[1,2], [3,4]],
                  [[5,6], [7,8]]])

print(ndarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [100]:
print(np.ones((4,3,2)))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [101]:
print(np.zeros((4,3,2)))

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [102]:
print(np.random.random((4,3,2)))

[[[0.30618802 0.58579294]
  [0.64695285 0.19209931]
  [0.77897744 0.49446904]]

 [[0.45095467 0.69795329]
  [0.95921832 0.73181042]
  [0.93703934 0.82782786]]

 [[0.54268059 0.47089053]
  [0.20469201 0.06859111]
  [0.30390197 0.91143979]]

 [[0.85102589 0.29647285]
  [0.1858351  0.58700824]
  [0.14506914 0.4158876 ]]]


In [105]:
arrflat = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

print(arrflat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [107]:
arrflat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### video

In [1]:
my_list = [1,2,3]

In [2]:
print(my_list)

[1, 2, 3]


In [3]:
my_list + [4,5]

[1, 2, 3, 4, 5]

In [4]:
print(my_list * 2)

[1, 2, 3, 1, 2, 3]


In [5]:
my_list.append(4)

In [6]:
print(my_list)

[1, 2, 3, 4]


In [7]:
my_list.extend([4,5,6])

In [9]:
print(my_list)

[1, 2, 3, 4, 4, 5, 6]


In [11]:
my_list.remove(4)

In [13]:
print(my_list)

[1, 2, 3, 4, 5, 6]


In [14]:
student = {'name': 'bella', 'age' : 20}


In [15]:
employee = {'ceo': {'name': 'edo', 'age' : 21}}

In [16]:
student = dict(name='yudo', age = 31)

In [17]:
print(student['name'])

yudo


In [18]:
print(student['age'])

31


In [19]:
print(student)

{'name': 'yudo', 'age': 31}


In [20]:
del student['age']

In [21]:
print(student)

{'name': 'yudo'}


In [22]:
print(student.keys())

dict_keys(['name'])


In [23]:
print(student.values())

dict_values(['yudo'])


### tuples

In [25]:
people = ('raka',('kode','random'))

In [26]:
print(people)

('raka', ('kode', 'random'))


In [27]:
print(people[0])

raka


In [28]:
print(people[1])

('kode', 'random')


In [29]:
print(people[1][0])

kode


In [30]:
numbers = (1,2,3,4)

In [31]:
new_numbers = numbers[0], numbers[1:3]

In [32]:
print(new_numbers)

(1, (2, 3))


In [33]:
print(numbers)

(1, 2, 3, 4)


In [34]:
email_attr = ('to', 'from', 'cc', 'bcc', 'subject', 'body')
email_attr_list = list(email_attr)
email_attr_list.sort()

In [35]:
print(email_attr_list)

['bcc', 'body', 'cc', 'from', 'subject', 'to']


In [36]:
myfile = open('text.txt', 'w')

In [37]:
myfile.write ('halo text file!\n')

16

In [38]:
myfile.write('good bye text file!\n')

20

In [39]:
myfile.close()

### While Loops

In [2]:
while test :
    statements
    if test : break
    if test : continue
else:
    statements

NameError: name 'test' is not defined

In [3]:
message = "spam"
while message  != '':
    print(message, end='')
    message = message[1:]

spampamamm

In [4]:
a = 0
b = 13
while a < b :
    print(a, end='')
    a = a + 1

0123456789101112

In [ ]:
for target in object:
    statement

In [5]:
x = 0
while (x < 100):
    x+=2
print(x)

100


In [7]:
for l in 'Idaz':
    if l == 'a':
        pass
    print(l, end=",")

I,d,a,z,

In [3]:
if not 1:
    print('true')
else:
    print('false')

false


In [5]:
age = input ('enter your age :')
if int (age) * 365 > 20000:
    print('Time to retire')
elif int (age) * 365 > 10000:
    print('LOts of time left!')
else :
    print('time to get started')

LOts of time left!


In [6]:
user_age = input('Enter your age: ')
age = int(user_age) * 365

if age >= 9490:
    print('you are a jedi master now. Go learn from master yoda!!')
elif age >= 8395 and age < 9490:
    print('becoming jedi knight')
else:
    print('you are a young padawan')

you are a young padawan


In [9]:
x = 10
y = 50

if(x**2 >100 and y < 100):
    print(x,y)

In [10]:
def outerFun(a,b):
    def innerFun(c,d):
        return c+d
    return innerFun(a,b)
res = outer
Fun(5,10)print(res)

SyntaxError: invalid syntax (1212139550.py, line 6)

In [2]:
import numpy as np

In [9]:
for i in 'Idaz' :
    if i == 'a' :
        pass
    print(i, end=",")

I,d,a,z,